# Generated by Django 4.2 on 2023-04-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans1',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quest',
            new_name='puzzle',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ans4',
        ),
    ]
