# Generated by Django 4.2 on 2023-05-01 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_rename_ans1_question_ans_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="id",
        ),
        migrations.AddField(
            model_name="question",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
